version: '2'
checks:
  argument-count:
    enabled: true
  file-lines:
    enabled: true
  method-lines:
    enabled: true
ratings:
  paths:
    - 'src/app/**/*.ts'
    - 'src/test/**/*.tsx'
    - '**/*.ts'
    - '**/*.tsx'
exclude_paths:
  - 'node_modules/'
  - 'test/'
  - '.next/'
